const plan={
0:{title:"Recovery Reset",emoji:"🌊",mission:"Swim, sauna and mobility. Recover hard so you can train hard.",recovery:["25–35 min easy/moderate swim","Dry/wood sauna 8–10 min","Jacuzzi 8–10 min","Chest, lats, hips, hamstrings, calves & thoracic mobility"]},
1:{title:"Chest Priority",emoji:"⚒️",mission:"Lower chest. Full chest shape. Shoulder width. Core control.",ex:[["Incline push-up activation",2,"8–12",45,"Stop 3 reps before failure."],["Incline dumbbell press",4,"8–10",90,"Upper chest structure and lift."],["Machine chest press / flat DB press",3,"8–10",90,"Overall chest strength."],["Assisted dips / decline chest press",4,"8–10",90,"Main lower chest priority."],["High-to-low cable fly",4,"12–15",60,"Lower chest line. Hard squeeze."],["Low-to-high cable fly",2,"12–15",60,"Upper chest balance."],["Seated shoulder press",3,"8–10",90,"Shoulder strength."],["Cable lateral raise",4,"12–15",50,"Side delts for width."],["Rope triceps pushdown",3,"12–15",60,"Triceps shape."],["Cable crunch",3,"12–15",60,"Controlled abs."]]},
2:{title:"Back + Pull",emoji:"🦍",mission:"Build the V-shape, posture, arm density and grip.",ex:[["Assisted pull-up",3,"6–8",90,"Clean reps; use enough assistance."],["Lat pulldown",3,"8–12",90,"Full stretch, elbows down."],["Chest-supported row",4,"8–12",90,"Back thickness."],["Seated cable row",3,"10–12",75,"Control posture."],["Straight-arm pulldown",3,"12–15",60,"Lat isolation."],["Face pulls",4,"15",60,"Non-negotiable posture work."],["Dumbbell curls",3,"10–12",60,"Biceps."],["Hammer curls",3,"10–12",60,"Forearm thickness."],["Reverse curls",3,"12",60,"Top-side forearm."],["Farmer carry",4,"30–40 sec",75,"Grip and wrist stability."]]},
3:{title:"Recovery Flow",emoji:"💧",mission:"Reset stress. Move, recover, hydrate.",recovery:["20–30 min easy/moderate swim","Steam sauna 8–12 min + cool shower","Jacuzzi 8–10 min","Stretch hips, hamstrings, chest, lats & calves","Water + electrolytes"]},
4:{title:"Legs + Glutes",emoji:"🦵",mission:"Knee-safe strength, posterior chain and core.",ex:[["Bike warm-up",1,"8–10 min",0,"Easy pace."],["Leg press / squat pattern",4,"8–10",105,"Controlled depth. No knee pain."],["Romanian deadlift",4,"8–10",90,"Posterior chain compound."],["Seated leg curl",3,"10–12",60,"Hamstrings."],["Hip thrust / glute bridge",3,"10–12",75,"Glutes and support."],["Leg extension",3,"12–15",60,"Only if knee feels fine."],["Calf raises",4,"12–15",50,"No bouncing."],["Hanging knee raise / captain chair",3,"8–12",60,"Abs."],["Plank",3,"45–60 sec",45,"Core stability."],["Pallof press",3,"12/side",45,"Anti-rotation."]]},
5:{title:"Visual Muscle Day",emoji:"🔥",mission:"Shoulders, arms, lower chest detail and whole forearm thickness.",ex:[["Machine shoulder press",3,"8–10",90,"Strong shoulders."],["Dumbbell lateral raise",4,"12–15",50,"Strict side delts."],["Cable lateral raise",3,"12–15",50,"Stretch and pump."],["Rear delt fly",4,"12–15",60,"Rear shoulders."],["Incline machine press",3,"10",90,"Moderate chest top-up."],["High-to-low cable fly",4,"12–15",60,"Lower chest priority."],["Assisted dips / dip machine",3,"8–10",75,"Clean reps."],["Push-up finisher",2,"Near failure",75,"Stop 1–2 reps before form breaks."],["EZ bar curl",3,"10–12",60,"Biceps."],["Rope hammer curl",3,"12",60,"Arms + forearms."],["Rope triceps pushdown",3,"12–15",60,"Triceps."],["Palm-side wrist curl",3,"12–15",45,"Forearm flexors."],["Reverse wrist curl",2,"15",45,"Top-side balance."]]},
6:{title:"5K + Abs",emoji:"🏃",mission:"Stamina and waist work without sacrificing size.",recovery:["5–8 min warm-up walk","5KM comfortable run — only if knee is pain-free","If knee isn't perfect: 25–35 min bike, incline walk or swim","Cable crunch 3 × 12–15","Dead bug 3 × 10/side","Side plank 2 × 30–45 sec/side"]}
};
let state={},view="today",timer=null,remaining=0,activeExercise=0;
try{state=JSON.parse(localStorage.getItem("forge")||"{}")||{}}catch(e){state={};try{localStorage.removeItem("forge")}catch(_){}}
window.addEventListener("error",function(e){var a=document.querySelector("#app");if(a&&!a.innerHTML.trim())a.innerHTML='<div style="padding:40px 20px;color:white;font-family:system-ui"><h2>Forge is recovering…</h2><p style="color:#9aa3b2">Refresh once to continue.</p></div>'});
const key=()=>{let d=new Date(),m=String(d.getMonth()+1).padStart(2,"0"),day=String(d.getDate()).padStart(2,"0");return d.getFullYear()+"-"+m+"-"+day};
const save=()=>{try{localStorage.setItem("forge",JSON.stringify(state))}catch(e){}};
const day=()=>plan[new Date().getDay()];
const ds=()=>state[key()]||(state[key()]={sets:{},done:{},nutrition:{}});
function toast(t){let x=document.querySelector("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1500)}
function previousSession(exerciseName){
 const dates=Object.keys(state).filter(x=>/^\d{4}-/.test(x)&&x<key()).sort().reverse();
 for(const date of dates){let pd=plan[new Date(date+"T12:00:00").getDay()],idx=(pd.ex||[]).findIndex(x=>x[0]===exerciseName);if(idx>=0&&state[date]?.sets?.[idx])return {date,sets:state[date].sets[idx]}}
 return null;
}
function setVal(i,s,k,v){let d=ds();d.sets[i]??={};d.sets[i][s]??={};d.sets[i][s][k]=v;save()}
function hit(i,s,sec){
 let d=ds();d.sets[i]??={};d.sets[i][s]??={};d.sets[i][s].hit=!d.sets[i][s].hit;save();
 if(d.sets[i][s].hit&&sec)startTimer(sec);render();
}
function completeExercise(i){
 ds().done[i]=true;save();
 let ex=day().ex||[];if(i<ex.length-1){activeExercise=i+1;toast("Exercise complete. Next up ⚡")}else toast("Workout complete. Strong work 🔥");
 render();
}
function startTimer(sec){clearInterval(timer);remaining=sec;renderRest();timer=setInterval(()=>{remaining--;renderRest();if(remaining<=0){clearInterval(timer);toast("Rest done. Next set ⚡")}},1000)}
function renderRest(){let e=document.querySelector("#rest");if(e)e.innerHTML=remaining>0?'<div><span class="eyebrow">REST TIMER</span><b>'+Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,"0")+'</b></div><button onclick="remaining=0;clearInterval(timer);renderRest()">Skip</button>':""}
function renderTop(){return '<div class="top"><div class="brand">FORGE</div><div class="avatar">P</div></div>'}
function nav(){var el=document.querySelector("#nav");var items=[["today","⌂","Today"],["progress","↗","Progress"],["fuel","◉","Fuel"],["more","☰","More"]];el.innerHTML=items.map(function(x){return '<button class="'+(view===x[0]?"active":"")+'" data-view="'+x[0]+'"><b>'+x[1]+'</b>'+x[2]+'</button>'}).join("");Array.prototype.forEach.call(el.querySelectorAll("button"),function(b){b.addEventListener("click",function(){view=b.getAttribute("data-view");render()})})}
function workoutFlow(d,data,ex){
 let completed=ex.filter((_,i)=>data.done[i]).length;
 if(data.done[activeExercise]){let n=ex.findIndex((_,i)=>i>activeExercise&&!data.done[i]);if(n>=0)activeExercise=n}
 let x=ex[activeExercise],prev=previousSession(x[0]),setData=data.sets?.[activeExercise]||{};
 let prevText=prev?Object.keys(prev.sets).map((s)=>{let v=prev.sets[s];return v.kg&&v.reps?(Number(s)+1)+": "+v.kg+"kg × "+v.reps:null}).filter(Boolean).join(" · "):"No previous logged session yet";
 let sets=Array.from({length:x[1]},(_,s)=>{let v=setData[s]||{},pv=prev?.sets?.[s]||{};return '<div class="set focus-set"><label>S'+(s+1)+'</label><div class="inputwrap"><input inputmode="decimal" placeholder="'+(pv.kg||"kg")+'" value="'+(v.kg||"")+'" onchange="setVal('+activeExercise+','+s+',\'kg\',this.value)"><small>KG</small></div><div class="inputwrap"><input inputmode="numeric" placeholder="'+(pv.reps||"reps")+'" value="'+(v.reps||"")+'" onchange="setVal('+activeExercise+','+s+',\'reps\',this.value)"><small>REPS</small></div><button class="'+(v.hit?"hit":"")+'" onclick="hit('+activeExercise+','+s+','+x[3]+')">✓</button></div>'}).join("");
 let allHit=Array.from({length:x[1]},(_,s)=>setData[s]?.hit).every(Boolean);
 return '<div class="flow-head"><span>Exercise '+(activeExercise+1)+' of '+ex.length+'</span><span>'+completed+' complete</span></div><div class="flow-progress"><i style="width:'+Math.round(completed/ex.length*100)+'%"></i></div><div class="exercise focus glass"><div class="ex-head"><div><div class="eyebrow">NOW TRAINING</div><h2>'+x[0]+'</h2><div class="meta">'+x[1]+' sets · '+x[2]+' reps · '+(x[3]?x[3]+'s rest':'warm-up')+'</div></div></div><div class="previous"><span>LAST TIME</span><b>'+prevText+'</b></div><div class="sets">'+sets+'</div><div class="coach-note">↳ '+x[4]+'</div><button class="cta '+(allHit?"ready":"")+'" onclick="completeExercise('+activeExercise+')">'+(allHit?"Complete exercise →":"Complete when ready →")+'</button></div><div class="exercise-nav"><button '+(activeExercise===0?"disabled":"")+' onclick="activeExercise--;render()">← Previous</button><button '+(activeExercise===ex.length-1?"disabled":"")+' onclick="activeExercise++;render()">Next →</button></div><div class="up-next"><div class="eyebrow">TODAY</div>'+ex.map((e,i)=>'<button class="'+(i===activeExercise?"current":"")+' '+(data.done[i]?"done":"")+'" onclick="activeExercise='+i+';render()"><span>'+(data.done[i]?"✓":i+1)+'</span>'+e[0]+'</button>').join("")+'</div>';
}
function today(){
 let d=day(),data=ds(),ex=d.ex||[],completed=Object.values(data.done).filter(Boolean).length,p=ex.length?Math.round(completed/ex.length*100):0;
 let body='<div class="hero compact"><div class="eyebrow">'+new Date().toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"short"})+'</div><h1>'+d.emoji+' '+d.title+'</h1><p>'+d.mission+'</p></div><div id="rest" class="rest glass"></div>';
 if(ex.length) body+=workoutFlow(d,data,ex);
 else body+='<div class="mission glass"><div class="mission-row"><div><div class="eyebrow">RECOVERY DAY</div><h3>'+completed+' / '+d.recovery.length+' complete</h3></div><div class="ring" style="--p:'+Math.round(completed/d.recovery.length*100)+'%"><b>'+Math.round(completed/d.recovery.length*100)+'%</b></div></div></div><div class="section-title"><h2>Recovery protocol</h2></div>'+d.recovery.map((x,i)=>'<div class="card glass nutrition-item"><span>'+x+'</span><button class="toggle '+(data.done[i]?"on":"")+'" onclick="ds().done['+i+']=!ds().done['+i+'];save();render()">'+(data.done[i]?"Done ✓":"Mark")+'</button></div>').join("");
 return body;
}
function fuel(){let n=ds().nutrition,items=[["protein","Protein","150–160g"],["water","Hydration","2.5–3.5L"],["creatine","Creatine","5g"],["calories","Calories",day().ex?"2300–2500":"2100–2300"]];return '<div class="hero"><div class="eyebrow">DAILY INPUT</div><h1>Fuel the work.</h1><p>Simple adherence. No food-diary clutter.</p></div><div class="card glass">'+items.map(function(x){return '<div class="nutrition-item"><div><b>'+x[1]+'</b><div class="meta">'+x[2]+'</div></div><button class="toggle '+(n[x[0]]?"on":"")+'" onclick="toggleNutrition(\''+x[0]+'\')">'+(n[x[0]]?"Done ✓":"Check")+'</button></div>'}).join("")+'</div>'}function toggleNutrition(k){ds().nutrition[k]=!ds().nutrition[k];save();render()}
function progress(){let dates=Object.keys(state).filter(x=>/^\d{4}-/.test(x)).sort(),sessions=dates.filter(x=>Object.values(state[x].done||{}).some(Boolean)).length;return '<div class="hero"><div class="eyebrow">PROGRESSION</div><h1>Proof, not vibes.</h1><p>Every logged set becomes your baseline for the next session.</p></div><div class="metric-grid"><div class="metric glass"><small>Logged days</small><strong>'+sessions+'</strong></div><div class="metric glass"><small>Goal range</small><strong>75–80kg</strong></div></div><div class="section-title"><h2>2-week review</h2><span>Fortnightly only</span></div><div class="card glass"><p class="meta">Weight average · waist · front/side/back photos · key lifts · knee status · nutrition consistency.</p><div class="note">The dedicated due-date check-in and photo flow is the next data layer.</div></div>'}
function more(){return '<div class="hero"><div class="eyebrow">THE SYSTEM</div><h1>Built for the block.</h1><p>75–80 kg recomposition. Wider, tighter, stronger — not a skinny cut.</p></div><div class="card glass"><div class="nutrition-item"><span>Lower chest priority</span><b>2× / week</b></div><div class="nutrition-item"><span>Forearms</span><b>2–3× / week</b></div><div class="nutrition-item"><span>Protein</span><b>150–160g</b></div><div class="nutrition-item"><span>Creatine</span><b>5g daily</b></div></div><div class="card glass"><div class="eyebrow">PROGRESSIVE OVERLOAD</div><p class="note">Hit every set at the top of its rep range with clean form? Increase the weight next time. Keep 1–2 reps in reserve on most sets.</p></div>'}
function render(){document.querySelector("#app").innerHTML=renderTop()+(view==="today"?today():view==="fuel"?fuel():view==="progress"?progress():more());nav();renderRest();window.scrollTo({top:0,behavior:"smooth"})}
render();