const plan={
0:{title:"Recovery Reset",emoji:"🌊",mission:"Swim, sauna and mobility. Recover hard so you can train hard.",recovery:["25–35 min easy/moderate swim","Dry/wood sauna 8–10 min","Jacuzzi 8–10 min","Chest, lats, hips, hamstrings, calves & thoracic mobility"]},
1:{title:"Chest Priority",emoji:"⚒️",mission:"Lower chest. Full chest shape. Shoulder width. Core control.",ex:[["Incline push-up activation",2,"8–12",45,"Stop 3 reps before failure."],["Incline dumbbell press",4,"8–10",90,"Upper chest structure and lift."],["Machine chest press / flat DB press",3,"8–10",90,"Overall chest strength."],["Assisted dips / decline chest press",4,"8–10",90,"Main lower chest priority."],["High-to-low cable fly",4,"12–15",60,"Lower chest line. Hard squeeze."],["Low-to-high cable fly",2,"12–15",60,"Upper chest balance."],["Seated shoulder press",3,"8–10",90,"Shoulder strength."],["Cable lateral raise",4,"12–15",50,"Side delts for width."],["Rope triceps pushdown",3,"12–15",60,"Triceps shape."],["Cable crunch",3,"12–15",60,"Controlled abs."]]},
2:{title:"Back + Pull",emoji:"🦍",mission:"Build the V-shape, posture, arm density and grip.",ex:[["Assisted pull-up",3,"6–8",90,"Clean reps; use enough assistance."],["Lat pulldown",3,"8–12",90,"Full stretch, elbows down."],["Chest-supported row",4,"8–12",90,"Back thickness."],["Seated cable row",3,"10–12",75,"Control posture."],["Straight-arm pulldown",3,"12–15",60,"Lat isolation."],["Face pulls",4,"15",60,"Non-negotiable posture work."],["Dumbbell curls",3,"10–12",60,"Biceps."],["Hammer curls",3,"10–12",60,"Forearm thickness."],["Reverse curls",3,"12",60,"Top-side forearm."],["Farmer carry",4,"30–40 sec",75,"Grip and wrist stability."]]},
3:{title:"Recovery Flow",emoji:"💧",mission:"Reset stress. Move, recover, hydrate.",recovery:["20–30 min easy/moderate swim","Steam sauna 8–12 min + cool shower","Jacuzzi 8–10 min","Stretch hips, hamstrings, chest, lats & calves","Water + electrolytes"]},
4:{title:"Legs + Glutes",emoji:"🦵",mission:"Knee-safe strength, posterior chain and core.",ex:[["Bike warm-up",1,"8–10 min",0,"Easy pace."],["Leg press / squat pattern",4,"8–10",105,"Controlled depth. No knee pain."],["Romanian deadlift",4,"8–10",90,"Posterior chain compound."],["Seated leg curl",3,"10–12",60,"Hamstrings."],["Hip thrust / glute bridge",3,"10–12",75,"Glutes and support."],["Leg extension",3,"12–15",60,"Only if knee feels fine."],["Calf raises",4,"12–15",50,"No bouncing."],["Hanging knee raise / captain chair",3,"8–12",60,"Abs."],["Plank",3,"45–60 sec",45,"Core stability."],["Pallof press",3,"12/side",45,"Anti-rotation."]]},
5:{title:"Visual Muscle Day",emoji:"🔥",mission:"Shoulders, arms, lower chest detail and whole forearm thickness.",ex:[["Machine shoulder press",3,"8–10",90,"Strong shoulders."],["Dumbbell lateral raise",4,"12–15",50,"Strict side delts."],["Cable lateral raise",3,"12–15",50,"Stretch and pump."],["Rear delt fly",4,"12–15",60,"Rear shoulders."],["Incline machine press",3,"10",90,"Moderate chest top-up."],["High-to-low cable fly",4,"12–15",60,"Lower chest priority."],["Assisted dips / dip machine",3,"8–10",75,"Clean reps."],["Push-up finisher",2,"Near failure",75,"Stop 1–2 reps before form breaks."],["EZ bar curl",3,"10–12",60,"Biceps."],["Rope hammer curl",3,"12",60,"Arms + forearms."],["Rope triceps pushdown",3,"12–15",60,"Triceps."],["Palm-side wrist curl",3,"12–15",45,"Forearm flexors."],["Reverse wrist curl",2,"15",45,"Top-side balance."]]},
6:{title:"5K + Abs",emoji:"🏃",mission:"Stamina and waist work without sacrificing size.",recovery:["5–8 min warm-up walk","5KM comfortable run — only if knee is pain-free","If knee isn't perfect: 25–35 min bike, incline walk or swim","Cable crunch 3 × 12–15","Dead bug 3 × 10/side","Side plank 2 × 30–45 sec/side"]}
};

let state={},view="today",timer=null,remaining=0,activeExercise=0,flowDay=null,timerPaused=false,restTarget="set",audioContext=null,forgeImage=null,forgeAbort=null,lastFocus=null;
try{state=JSON.parse(localStorage.getItem("forge")||"{}")||{}}catch(e){state={};try{localStorage.removeItem("forge")}catch(_){} }
window.addEventListener("error",function(){const app=document.querySelector("#app");if(app&&!app.innerHTML.trim())app.innerHTML='<div class="fatal"><h2>Forge is recovering…</h2><p>Refresh once to continue.</p></div>'});

const key=()=>{const d=new Date(),m=String(d.getMonth()+1).padStart(2,"0"),n=String(d.getDate()).padStart(2,"0");return d.getFullYear()+"-"+m+"-"+n};
const save=()=>{try{localStorage.setItem("forge",JSON.stringify(state))}catch(e){} };
const day=()=>plan[new Date().getDay()];
const ds=()=>state[key()]||(state[key()]={sets:{},done:{},nutrition:{},overrides:{}});
const settings=()=>state.settings||(state.settings={voiceRest:true,soundRest:true,vibrateRest:true});
const escapeHtml=(value)=>String(value??"").replace(/[&<>'"]/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

function toast(text){const el=document.querySelector("#toast");el.textContent=text;el.classList.add("show");clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>el.classList.remove("show"),2200)}
function previousSession(exerciseName){const dates=Object.keys(state).filter(x=>/^\d{4}-/.test(x)&&x<key()).sort().reverse();for(const date of dates){const previousPlan=plan[new Date(date+"T12:00:00").getDay()],idx=(previousPlan.ex||[]).findIndex(x=>x[0]===exerciseName);if(idx>=0&&state[date]?.sets?.[idx])return {date,sets:state[date].sets[idx]}}return null}
function setVal(i,s,k,v){const data=ds();data.sets[i]??={};data.sets[i][s]??={};data.sets[i][s][k]=v;save()}
function hit(i,s,sec){primeCoachAudio();const data=ds();data.sets[i]??={};data.sets[i][s]??={};data.sets[i][s].hit=!data.sets[i][s].hit;save();if(data.sets[i][s].hit&&sec){const total=day().ex?.[i]?.[1]||0,allHit=Array.from({length:total},(_,index)=>data.sets[i]?.[index]?.hit).every(Boolean);startTimer(sec,allHit?"exercise":"set")}render()}
function completeExercise(i){ds().done[i]=true;save();const exercises=day().ex||[];if(i<exercises.length-1){activeExercise=i+1;toast("Exercise complete. Next up ⚡")}else toast("Workout complete. Strong work 🔥");render()}

function primeCoachAudio(){try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();if(audioContext.state==="suspended")audioContext.resume()}catch(e){}}
function speak(text){if(!settings().voiceRest||!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.rate=1.02;utterance.pitch=.96;utterance.volume=1;window.speechSynthesis.speak(utterance)}
function chime(){if(!settings().soundRest)return;primeCoachAudio();if(!audioContext)return;try{const now=audioContext.currentTime;[523.25,659.25,783.99].forEach((frequency,index)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.0001,now+index*.11);gain.gain.exponentialRampToValueAtTime(.16,now+index*.11+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+index*.11+.22);oscillator.connect(gain).connect(audioContext.destination);oscillator.start(now+index*.11);oscillator.stop(now+index*.11+.24)})}catch(e){}}
function finishRest(){clearInterval(timer);timer=null;remaining=0;timerPaused=false;chime();if(settings().vibrateRest&&navigator.vibrate)navigator.vibrate([100,60,160]);const message=restTarget==="exercise"?"Rest complete. Let’s move to your next exercise.":"Let’s go! Time for your next set.";speak(message);toast(restTarget==="exercise"?"Rest done. Next exercise ⚡":"Rest done. Next set ⚡");renderRest()}
function timerTick(){if(timerPaused)return;remaining=Math.max(0,remaining-1);if(remaining===10)speak("Get ready. Rest time is almost over.");if(remaining>0&&remaining<=5)speak(String(remaining));if(remaining===0)finishRest();else renderRest()}
function startTimer(sec,target="set"){clearInterval(timer);remaining=sec;restTarget=target;timerPaused=false;renderRest();timer=setInterval(timerTick,1000)}
function skipRest(){clearInterval(timer);timer=null;remaining=0;timerPaused=false;if("speechSynthesis" in window)window.speechSynthesis.cancel();renderRest();toast("Rest skipped")}
function togglePause(){timerPaused=!timerPaused;renderRest()}
function addRest(){remaining+=30;renderRest();toast("30 seconds added")}
function toggleSetting(name){settings()[name]=!settings()[name];save();if(name==="voiceRest"&&settings()[name]){primeCoachAudio();speak("Voice coaching on")}render()}
function renderRest(){const el=document.querySelector("#rest");if(!el)return;if(remaining<=0){el.innerHTML="";return}el.innerHTML='<div class="rest-time"><span class="eyebrow">REST TIMER</span><b>'+Math.floor(remaining/60)+':'+String(remaining%60).padStart(2,"0")+'</b><span class="rest-status">'+(timerPaused?"Paused":restTarget==="exercise"?"Next exercise":"Next set")+'</span></div><div class="rest-actions"><button type="button" onclick="addRest()" aria-label="Add 30 seconds">+30</button><button type="button" onclick="togglePause()" aria-label="'+(timerPaused?"Resume":"Pause")+' timer">'+(timerPaused?"▶":"Ⅱ")+'</button><button type="button" onclick="skipRest()">Skip</button></div>'}

function renderTop(){return '<div class="top"><div class="brand">FORGE</div><div class="avatar" aria-label="Profile">P</div></div>'}
function nav(){const el=document.querySelector("#nav"),items=[["today","⌂","Today"],["progress","↗","Progress"],["fuel","◉","Fuel"],["more","☰","More"]];el.innerHTML=items.map(x=>'<button type="button" class="'+(view===x[0]?"active":"")+'" data-view="'+x[0]+'"><b aria-hidden="true">'+x[1]+'</b>'+x[2]+'</button>').join("");el.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{view=button.dataset.view;render()}))}

function workoutFlow(d,data,ex){
 const completed=ex.filter((_,i)=>data.done[i]).length;if(flowDay!==key()){const next=ex.findIndex((_,i)=>!data.done[i]);activeExercise=next>=0?next:Math.max(0,ex.length-1);flowDay=key()}
 const x=ex[activeExercise],override=data.overrides?.[activeExercise],displayName=override?.name||x[0],prev=previousSession(x[0]),setData=data.sets?.[activeExercise]||{};
 const prevText=prev?Object.keys(prev.sets).map(s=>{const v=prev.sets[s];return v.kg&&v.reps?(Number(s)+1)+": "+v.kg+"kg × "+v.reps:null}).filter(Boolean).join(" · "):"No previous logged session yet";
 const sets=Array.from({length:x[1]},(_,s)=>{const v=setData[s]||{},pv=prev?.sets?.[s]||{};return '<div class="set focus-set"><label for="kg-'+activeExercise+'-'+s+'">S'+(s+1)+'</label><div class="inputwrap"><input id="kg-'+activeExercise+'-'+s+'" inputmode="decimal" aria-label="Set '+(s+1)+' weight in kilograms" placeholder="'+escapeHtml(pv.kg||"kg")+'" value="'+escapeHtml(v.kg||"")+'" onchange="setVal('+activeExercise+','+s+',\'kg\',this.value)"><small>KG</small></div><div class="inputwrap"><input inputmode="numeric" aria-label="Set '+(s+1)+' repetitions" placeholder="'+escapeHtml(pv.reps||"reps")+'" value="'+escapeHtml(v.reps||"")+'" onchange="setVal('+activeExercise+','+s+',\'reps\',this.value)"><small>REPS</small></div><button type="button" class="'+(v.hit?"hit":"")+'" aria-label="Mark set '+(s+1)+' '+(v.hit?"not complete":"complete")+'" aria-pressed="'+Boolean(v.hit)+'" onclick="hit('+activeExercise+','+s+','+x[3]+')">✓</button></div>'}).join("");
 const allHit=Array.from({length:x[1]},(_,s)=>setData[s]?.hit).every(Boolean);
 return '<div class="flow-head"><span>Exercise '+(activeExercise+1)+' of '+ex.length+'</span><span>'+completed+' complete</span></div><div class="flow-progress" aria-label="'+completed+' of '+ex.length+' exercises complete"><i style="width:'+Math.round(completed/ex.length*100)+'%"></i></div><section class="exercise focus glass" aria-labelledby="current-exercise"><div class="ex-head"><div><div class="eyebrow">NOW TRAINING</div><h2 id="current-exercise">'+escapeHtml(displayName)+'</h2>'+(override?'<div class="replacement-tag">↳ Replaced '+escapeHtml(x[0])+'</div>':'')+'<div class="meta">'+x[1]+' sets · '+x[2]+' reps · '+(x[3]?x[3]+'s rest':'warm-up')+'</div></div></div><button type="button" class="ask-forge" onclick="openForgeCoach()"><span class="spark" aria-hidden="true">✦</span><span><b>Ask Forge</b><small>Swap a machine, check a photo, adjust the exercise</small></span><span aria-hidden="true">›</span></button><div class="previous"><span>LAST TIME</span><b>'+prevText+'</b></div><div class="sets">'+sets+'</div><div class="coach-note">↳ '+escapeHtml(x[4])+'</div><button type="button" class="cta '+(allHit?"ready":"")+'" onclick="completeExercise('+activeExercise+')">'+(allHit?"Complete exercise →":"Complete when ready →")+'</button></section><div class="exercise-nav"><button type="button" '+(activeExercise===0?"disabled":"")+' onclick="goToExercise('+(activeExercise-1)+')">← Previous</button><button type="button" '+(activeExercise===ex.length-1?"disabled":"")+' onclick="goToExercise('+(activeExercise+1)+')">Next →</button></div><div class="up-next"><div class="eyebrow">TODAY</div>'+ex.map((item,i)=>'<button type="button" class="'+(i===activeExercise?"current":"")+' '+(data.done[i]?"done":"")+'" onclick="goToExercise('+i+')"><span>'+(data.done[i]?"✓":i+1)+'</span>'+escapeHtml(data.overrides?.[i]?.name||item[0])+'</button>').join("")+'</div>'}
function goToExercise(index){const ex=day().ex||[];if(index<0||index>=ex.length)return;activeExercise=index;render()}
function today(){const d=day(),data=ds(),ex=d.ex||[],completed=Object.values(data.done).filter(Boolean).length;let body='<div class="hero compact"><div class="eyebrow">'+new Date().toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"short"})+'</div><h1>'+d.emoji+' '+d.title+'</h1><p>'+d.mission+'</p></div><div id="rest" class="rest glass" aria-live="polite"></div>';if(ex.length)body+=workoutFlow(d,data,ex);else body+='<div class="mission glass"><div class="mission-row"><div><div class="eyebrow">RECOVERY DAY</div><h3>'+completed+' / '+d.recovery.length+' complete</h3></div><div class="ring" style="--p:'+Math.round(completed/d.recovery.length*100)+'%"><b>'+Math.round(completed/d.recovery.length*100)+'%</b></div></div></div><div class="section-title"><h2>Recovery protocol</h2></div>'+d.recovery.map((x,i)=>'<div class="card glass nutrition-item"><span>'+x+'</span><button type="button" class="toggle '+(data.done[i]?"on":"")+'" onclick="ds().done['+i+']=!ds().done['+i+'];save();render()">'+(data.done[i]?"Done ✓":"Mark")+'</button></div>').join("");return body}
function fuel(){const n=ds().nutrition,items=[["protein","Protein","150–160g"],["water","Hydration","2.5–3.5L"],["creatine","Creatine","5g"],["calories","Calories",day().ex?"2300–2500":"2100–2300"]];return '<div class="hero"><div class="eyebrow">DAILY INPUT</div><h1>Fuel the work.</h1><p>Simple adherence. No food-diary clutter.</p></div><div class="card glass">'+items.map(x=>'<div class="nutrition-item"><div><b>'+x[1]+'</b><div class="meta">'+x[2]+'</div></div><button type="button" class="toggle '+(n[x[0]]?"on":"")+'" onclick="toggleNutrition(\''+x[0]+'\')">'+(n[x[0]]?"Done ✓":"Check")+'</button></div>').join("")+'</div>'}
function toggleNutrition(k){ds().nutrition[k]=!ds().nutrition[k];save();render()}
function progress(){const dates=Object.keys(state).filter(x=>/^\d{4}-/.test(x)).sort(),sessions=dates.filter(x=>Object.values(state[x].done||{}).some(Boolean)).length;return '<div class="hero"><div class="eyebrow">PROGRESSION</div><h1>Proof, not vibes.</h1><p>Every logged set becomes your baseline for the next session.</p></div><div class="metric-grid"><div class="metric glass"><small>Logged days</small><strong>'+sessions+'</strong></div><div class="metric glass"><small>Goal range</small><strong>75–80kg</strong></div></div><div class="section-title"><h2>2-week review</h2><span>Fortnightly only</span></div><div class="card glass"><p class="meta">Weight average · waist · front/side/back photos · key lifts · knee status · nutrition consistency.</p><div class="note">The dedicated due-date check-in and photo flow is the next data layer.</div></div>'}
function settingRow(keyName,title,detail){const on=settings()[keyName];return '<div class="setting-row"><div><b>'+title+'</b><span>'+detail+'</span></div><button type="button" class="switch '+(on?"on":"")+'" role="switch" aria-checked="'+on+'" onclick="toggleSetting(\''+keyName+'\')"><span></span></button></div>'}
function more(){return '<div class="hero"><div class="eyebrow">THE SYSTEM</div><h1>Built for the block.</h1><p>75–80 kg recomposition. Wider, tighter, stronger — not a skinny cut.</p></div><div class="section-title"><h2>Rest coaching</h2><span>During workouts</span></div><div class="card glass settings-card">'+settingRow("voiceRest","Voice countdown","Cue at 10 seconds, then count 5 to 1")+settingRow("soundRest","Finish chime","Play a short sound when rest ends")+settingRow("vibrateRest","Vibration","Vibrate when supported by your phone")+'</div><div class="card glass"><div class="nutrition-item"><span>Lower chest priority</span><b>2× / week</b></div><div class="nutrition-item"><span>Forearms</span><b>2–3× / week</b></div><div class="nutrition-item"><span>Protein</span><b>150–160g</b></div><div class="nutrition-item"><span>Creatine</span><b>5g daily</b></div></div><div class="card glass"><div class="eyebrow">PROGRESSIVE OVERLOAD</div><p class="note">Hit every set at the top of its rep range with clean form? Increase the weight next time. Keep 1–2 reps in reserve on most sets.</p></div>'}

function forgeContext(){const x=day().ex?.[activeExercise];return x?{name:x[0],sets:x[1],reps:x[2],rest:x[3],note:x[4],day:day().title}:null}
function openForgeCoach(){const dialog=document.querySelector("#forge-dialog"),context=forgeContext();if(!dialog||!context)return;lastFocus=document.activeElement;forgeImage=null;document.querySelector("#forge-exercise-name").textContent=ds().overrides?.[activeExercise]?.name||context.name;document.querySelector("#forge-question").value="";document.querySelector("#forge-preview").innerHTML="";document.querySelector("#forge-answer").innerHTML="";document.querySelector("#forge-submit").disabled=false;dialog.showModal();setTimeout(()=>document.querySelector("#forge-question").focus(),50)}
function closeForgeCoach(){const dialog=document.querySelector("#forge-dialog");forgeAbort?.abort();forgeAbort=null;if(dialog.open)dialog.close();lastFocus?.focus()}
function usePrompt(button){document.querySelector("#forge-question").value=button.dataset.prompt;document.querySelector("#forge-question").focus()}
async function handleForgePhoto(input){const file=input.files?.[0],preview=document.querySelector("#forge-preview");forgeImage=null;preview.innerHTML="";if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)){input.value="";toast("Use a JPG, PNG or WebP photo");return}if(file.size>10*1024*1024){input.value="";toast("Photo must be under 10 MB");return}try{forgeImage=await resizePhoto(file);preview.innerHTML='<div class="photo-preview"><img src="'+forgeImage+'" alt="Selected gym machine"><button type="button" onclick="removeForgePhoto()" aria-label="Remove selected photo">×</button></div><span>Photo ready for Forge</span>'}catch(e){toast("Couldn’t prepare that photo. Try another one.")}}
function resizePhoto(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=reject;reader.onload=()=>{const image=new Image();image.onerror=reject;image.onload=()=>{const max=1280,scale=Math.min(1,max/Math.max(image.width,image.height)),canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext("2d").drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL("image/jpeg",.8))};image.src=reader.result};reader.readAsDataURL(file)})}
function removeForgePhoto(){forgeImage=null;document.querySelector("#forge-photo").value="";document.querySelector("#forge-preview").innerHTML=""}
function renderForgeAnswer(payload){const answer=document.querySelector("#forge-answer"),replacement=payload.replacement?.trim();answer.innerHTML='<div class="forge-result"><div class="result-label">FORGE SAYS</div><p>'+escapeHtml(payload.answer).replace(/\n/g,"<br>")+'</p>'+(payload.caution?'<div class="caution">'+escapeHtml(payload.caution)+'</div>':'')+(replacement?'<button type="button" class="apply-swap" data-replacement="'+escapeHtml(replacement)+'">Use '+escapeHtml(replacement)+' today</button>':'')+'</div>';answer.querySelector(".apply-swap")?.addEventListener("click",event=>applyReplacement(event.currentTarget.dataset.replacement))}
async function askForge(event){event.preventDefault();const question=document.querySelector("#forge-question").value.trim(),answer=document.querySelector("#forge-answer"),submit=document.querySelector("#forge-submit");if(!question&&!forgeImage){answer.innerHTML='<div class="inline-error">Ask a question or add a machine photo first.</div>';return}submit.disabled=true;submit.innerHTML='<span class="spinner" aria-hidden="true"></span> Forge is checking…';answer.innerHTML='<div class="forge-thinking" role="status">Reviewing this exercise'+(forgeImage?" and your photo":"")+'…</div>';forgeAbort=new AbortController();try{const response=await fetch("/api/ask-forge",{method:"POST",headers:{"Content-Type":"application/json"},signal:forgeAbort.signal,body:JSON.stringify({question,image:forgeImage,exercise:forgeContext()})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"Forge couldn’t answer right now.");renderForgeAnswer(payload)}catch(error){if(error.name!=="AbortError")answer.innerHTML='<div class="inline-error">'+escapeHtml(error.message)+' <button type="button" onclick="document.querySelector(\'#forge-form\').requestSubmit()">Try again</button></div>'}finally{forgeAbort=null;submit.disabled=false;submit.textContent="Ask Forge"}}
function applyReplacement(name){const data=ds(),original=day().ex[activeExercise][0];data.overrides??={};data.overrides[activeExercise]={name,original,source:"Ask Forge",savedAt:new Date().toISOString()};save();closeForgeCoach();toast(name+" set for today");render()}

function render(){document.querySelector("#app").innerHTML=renderTop()+(view==="today"?today():view==="fuel"?fuel():view==="progress"?progress():more());nav();renderRest();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelector("#forge-dialog")?.addEventListener("click",event=>{if(event.target===event.currentTarget)closeForgeCoach()});
document.querySelector("#forge-dialog")?.addEventListener("cancel",event=>{event.preventDefault();closeForgeCoach()});
render();
